import coreWebVitals from "eslint-config-next/core-web-vitals";
import typescript from "eslint-config-next/typescript";

const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      // Generated by drizzle-kit; not ours to lint.
      "drizzle/**",
      "test-results/**",
      "playwright-report/**",
    ],
  },
  ...coreWebVitals,
  ...typescript,
];

export default config;
